name: incubyte_string_calculator
description: A TDD implementation of the String Calculator kata
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

dependencies:
  # No external dependencies - using only Dart standard library
